### ISSUE TITLE
Consider 'cutting ties' with the repo you forked from

### ISSUE THREAD

**Issue by eddelbuettel** [fboehm/qtlbim#6]
Your repo is currently listed as

![image](https://user-images.githubusercontent.com/673121/105647839-df8df200-5e6d-11eb-8713-fb379e9bce2f.png)

which means it is not a 'genuine' repo (as it is stated as a fork).  As described in [this page of the GitHub documentation](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile), contributions to such repositories "do not count".  It is not the most important thing in the world but if you plan to make more changes here you may want to follow the route described on that page and ask GitHub to 'cut' you from the CRAN/qtlbim repo you started from.  I think I have done that twice myself in the last decade, and it only takes an email ... and within a few days they usually respond.  And you have what seems like a valid case of rejuvenating a dormant -- yet useful! -- repo.

**Comment by fboehm** [comment]
Good idea! I didn't know that this could be done. I've now emailed Github support.

**Comment by fboehm** [comment]
github support approved the request.
